variables:
  HOST_REPO_PIPELINE_URL: 'https:\/\/gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com\/'
  HOST_REPO_URL: 'git@gitlab.com:'

default:
  # The version must match the minimum version declared in rush.json
  image: node:14

include:
  - local: 'ci/utils/base-job.yml'
  - local: 'ci/utils/condition.yml'
  - local: 'ci/modules/heart-api.yml'
  - local: 'ci/modules/heart-bigquery.yml'
  - local: 'ci/modules/heart-cli.yml'
  - local: 'ci/modules/heart-core.yml'
  - local: 'ci/modules/heart-dareboost.yml'
  - local: 'ci/modules/heart-lighthouse.yml'
  - local: 'ci/modules/heart-observatory.yml'
  - local: 'ci/modules/heart-greenit.yml'
  - local: 'ci/modules/heart-slack.yml'
  - local: 'ci/modules/heart-ssllabs-server.yml'
  - local: 'ci/website.yml'

ðŸ— Build for master:
  extends:
    - .install
    - .build
    - .only-master
  interruptible: true

ðŸ— Build for MR:
  extends:
    - .install
    - .build
    - .only-mr
  interruptible: true

# Checks code linting
ðŸ’… Lint:
  stage: test
  extends:
    - .install
    - .only-mr
  dependencies:
    - ðŸ— Build for MR
  script:
    - node common/scripts/install-run-rush.js lint
  interruptible: true

# Checks that a changelog has been provided
ðŸ“ Missing changelog:
  stage: test
  extends:
    - .install
    - .only-mr
  dependencies:
    - ðŸ— Build for MR
  script:
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -a
    # Checks that a changelog has been provided, regarding the target branch
    - node common/scripts/install-run-rush.js change
      --target-branch origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      --verify
  interruptible: true

ðŸ› Test:
  extends:
    - .test
    - .only-mr
  dependencies:
    - ðŸ— Build for MR
  script:
    - node common/scripts/install-run-rush.js test --verbose
  interruptible: true

# Publish packages to NPM.
# By default, the dry-run mode is enabled and the policy version is set to individualVersion.
# These two behaviors can be changed with the PUBLISH and VERSION_POLICY variables.
# This job is only triggered:
# - if the pipeline as been created from the Gitlab web interface (only:web)
# - if the branch name is `master` (only:branches and only:/^master$/)
# - if the user clicks on the 'play' button and has enough rights to write on this branch (when:manual)
ðŸš€ Publish the packages to NPM:
  stage: deploy
  extends:
    - .install
    - .only-master
  only:
    - web
  variables:
    PUBLISH: 0
    VERSION_POLICY: "individualVersion"
  dependencies:
    - ðŸ— Build for master
  script:
    # These values must be set to make Rush works
    - git config --local user.name "FABERNOVEL"
    - git config --local user.email "heart@fabernovel.com"
    # Create the --publish option for rush publish command.
    - if (( $PUBLISH == 1 )); then PUBLISH_OPTION="--publish"; else PUBLISH_OPTION=""; fi
    # Fix 'npm cannot run in wd' error
    - echo 'unsafe-perm = true' >> ~/.npmrc
    - echo "Publishing to NPM the packages with the ${VERSION_POLICY} version policy..."
    # Update the rush.json repository url with the one from the repo, to make the rush publish commands
    - sed -i -e "s/$HOST_REPO_PIPELINE_URL/$HOST_REPO_URL/g" rush.json
    - node common/scripts/install-run-rush.js version
      --bump
      --target-branch $CI_COMMIT_REF_NAME
      --version-policy $VERSION_POLICY
    # $CI_COMMIT_REF_NAME is 'master', as long as this job is restricted to run on the 'master' branch
    - node common/scripts/install-run-rush.js publish
      --include-all
      $PUBLISH_OPTION
      --set-access-level public
      --target-branch $CI_COMMIT_REF_NAME
      --version-policy $VERSION_POLICY
